### ISSUE TITLE
Ability to individually control if a card can be dragged

### ISSUE THREAD

**Issue by acroyear** [asseinfo/react-kanban#351]
In my app, I have fixed cards that represent wrappers around the cards that can actually be moved around (e.g., albums, folders, artists).  I'd like to be able to block the dragging action in these case, by having either a property in the card, or a a preDragStart event that I can use to answer yes/no if the card can be moved.

Yes, I know it kind of violates the general trend of the open kanban idea, but there may be, in process workflow uses, reasons why a card shouldn't be moved yet. One example, if you have a checklist in in an agile board, and should block moving it on until the checklist items are all flagged complete. Card ownership and permissions is another possible use case.

**Comment by Sabrinovsky** [comment]
Hi @acroyear , thanks for the ideia!

We'll think about it.

Until then, have you ever tried the [renderColumnHeader](https://github.com/lourenci/react-kanban#rendercolumnheader) ? 

You can create your own columnHeader and no need to use a card as wrapper

**Comment by lourenci** [comment]
Hi, @acroyear. I think your issue is related to this one #289.

We don't have this kind of control over the `onDrag` events. We are built on top of `react-beautiful-dnd` lib, we depend on that lib for that. As soon as they merge this [PR](https://github.com/atlassian/react-beautiful-dnd/pull/1764), we could allow this kind of control.

For the time being, I think we can work on top of the `isDragDisabled` prop. In our lib, this flag is global for all the cards or/and lanes, but I think it's not hard to provide a per-card control over this prop. For that, we'll have to have an way to flag a card as not draggable. Do you guys have any idea about that?

**Comment by lourenci** [comment]
Sorry, but, are you using the controlled board? If so, you can just do anything on the drag events.

**Comment by acroyear** [comment]
well for now, because i'm totally controlled, the item dragged out just pops back into place and i'm able to do the 'copy' (same content, new uuid for the id) to get the behavior I want.  Also, i've reworked the idea and dragging those items is now a valid use-case (e.g., if i drag an album onto a editable playlist, it fetches all the songs from the album and adds them).

been actually very happy with how the app is turning out so this is more a nice-to-have. The library has been working very well.

**Comment by lourenci** [comment]
Thanks for your feedback, @acroyear. I think this kind of feature is well welcome to the lib, since this is not the only issue about that.

Is your app open source? It would be nice if we can see what the community is working on on top of the react-kanban lib.

**Comment by acroyear** [comment]
It effectively is but it needs a server to talk to.   my usual 'test' server for public demos doesn't support the features that this app is using so i can't really share it as such. i need to stage a new one somewhere.  Here's a screenshot, though.

[Screenshot](https://subfiresuite.com/caps/uploads/big/c52f6e32d2ecb076f5e5d54656c555e1.png)
