### ISSUE TITLE
Card has inline block causing issues with width

### ISSUE THREAD

**Issue by jrock2004** [asseinfo/react-kanban#442]
![image](https://user-images.githubusercontent.com/655716/119052980-69207d00-b993-11eb-8fc9-7c67009dfe10.png)

So I am trying to build my own cards but they are not taking up the full width because of the inline block parent. As of now there is not an easy way to target that div to override it myself. Maybe I am missing something?

![image](https://user-images.githubusercontent.com/655716/119053032-7c334d00-b993-11eb-9cbf-f34c510c0a6a.png)

**Comment by Sabrinovsky** [comment]
Hi, you're right. You wont easily overwrite this css.
The problem is here: `<div style={{ display: 'inline-block', whiteSpace: 'normal' }}>{renderCard(isDragging)}</div>`
src/components/Board/components/Column/components/Card/index.js:14

We should remove this css, but i'm not sure if will cause any problems for other users. Or we should let the user overwrite it easily.

I'm kind a busy with college, so i dont know if i'll have time for check this but i'll try. Also, if you want to, we appreciate a PR.

**Comment by Sabrinovsky** [comment]
This is being solved soon on https://github.com/asseinfo/react-kanban/issues/453
